{ inputs, config, pkgs, ... }: {
  homebrew = {
    enable = true;
    caskArgs.no_quarantine = true;
    onActivation = {
      autoUpdate = false;
      upgrade = false;
      cleanup =
        "zap"; # "uninstall"; # should maybe be "zap" - remove anything not listed here
    };
    global = { brewfile = true; };

    taps = [
      "homebrew/bundle"
      "homebrew/cask"
      "homebrew/cask-fonts"
      "homebrew/core"
      "homebrew/services"
      "koekeishiya/formulae"
      "fujiapple852/trippy"
      "kreuzwerker/taps"
      "systemcraftsman/strimzi-kafka-cli"
      "metalbear-co/mirrord"
      "warrensbox/tap"
    ];

    casks = [
      "dash" # offline developer docs
      "discord"
      "gpg-suite"
      "pomatez" # pomodoro timer, but installs itself as startup item and doesn't
      "pgadmin4"
      "alacritty"
      "gpg-suite"
      "kui"
      "pgadmin4"
      "swiftdefaultappsprefpane"
      "default-folder-x"
      "discord"
      "wireshark"
    ];

    masApps = { };
    brews = [
      "trippy" # an mtr alternative
      "pre-commit"
      "lua"
      "luajit"
      "luv"
      "lz4"
      "lzo"
      "m1-terraform-provider-helper"
      "m4"
      "mirrord"
      "mpdecimal"
      "msgpack"
      "neovim"
      "nettle"
      "node"
      "oniguruma"
      "openjdk"
      "openssl@1.1"
      "p11-kit"
      "pcre2"
      "pixman"
      "pkg-config"
      "postgresql@14"
      "pre-commit"
      "pygments"
      "python-tabulate"
      "python-typing-extensions"
      "python@3.10"
      "python@3.11"
      "pyyaml"
      "readline"
      "serverless"
      "six"
      "sqlite"
      "steampipe"
      "strimzi-kafka-cli"
      "terraform-docs"
      "terragrunt"
      "tflint"
      "tfswitch"
      "tgswitch"
      "tree-sitter"
      "unbound"
      "unibilium"
      "virtualenv"
      "xorgproto"
      "xz"
      "zstd"
      "libxcb"
      "ansiweather"
      "libxdmcp"
      "awk"
      "libxext"
      "aws-iam-authenticator"
      "libxrender"
      "bdw-gc"
      "libyaml"
      "brotli"
      "little-cms2"
      "c-ares"
      "ca-certificates"
      "cairo"
      "cookiecutter"
      "docker-compose"
      "docker-credential-helper"
      "eksctl"
      "fontconfig"
      "freetype"
      "gdbm"
      "gettext"
      "giflib"
      "glib"
      "gmp"
      "gnutls"
      "go"
      "goreleaser"
      "graphite2"
      "guile"
      "harfbuzz"
      "icu4c"
      "jpeg-turbo"
      "jq"
      "just"
      "k6"
      "ko"
      "krb5"
      "kustomize"
      "libevent"
      "libgcrypt"
      "libgpg-error"
      "libidn2"
      "libmaxminddb"
      "libnghttp2"
      "libpng"
      "libpq"
      "libsmi"
      "libssh"
      "libtasn1"
      "libtermkey"
      "libtiff"
      "libtool"
      "libunistring"
      "libuv"
      "libvterm"
      "libx11"
      "libxau"
    ];
  };
}
