require('impatient')
require('config.options')
require('config.cmp')
require('config.treesitter')
require('config.telescope')
require('config.lualine')
require('config.tree')
require('config.dap')
require('config.telescope-dap')
require('config.keymaps')
require('config.autopairs')

